version: '3.6'

services:

  keycloak-db:
    image: mariadb:10
    command: --lower-case-table-names=1
    environment:
      - 'MYSQL_ROOT_PASSWORD=db-root-password'
      - 'MYSQL_DATABASE=keycloak'
      - 'MYSQL_USER=keycloak'
      - 'MYSQL_PASSWORD=db-password'

  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    command:
      - start-dev
      - --import-realm
    depends_on:
      - keycloak-db
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=keycloak-admin-password
      - KC_DB=mariadb
      - KC_DB_URL=jdbc:mariadb://keycloak-db:3306/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=db-password
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME_URL=http://localhost:18080
    ports:
      - 18080:8080 # http
    volumes:
      - ./test-realm.json:/opt/keycloak/data/import/test-realm.json
